name: Deploy Calculate Date to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'calculate-date/**'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
          cd calculate-date
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: calculate-date/dist
          branch: gh-pages
          target-folder: calculate-date
